### ISSUE TITLE
Separate Ready Valid Interface for AA/CRC and Data

### ISSUE THREAD

**Issue by Fibonacci12358** [tapeout/ble-baseband#6]
This is needed so the DMA knows when to read the AA/CRC bits from the Disassembler and so FIFO's can be inserted between the DMA and the Disassembler if needed.

**Comment by edwardcwang** [comment]
@Fibonacci12358 @jerryduan07 @alanzhengyl Could y'all double check if this is still valid?

**Comment by edwardcwang** [comment]
Fixed apparently
